# set name of your service
name: cookiesync

# default paramenters
env: {{ ENV }}
listen: "{{ HOST|default('0.0.0.0')}}:{{PORT|default(8080) }}"
redis_dsn: "{{ REDIS_DSN|default('redis://redis:6379') }}"
ch_dsn: "{{CHP_DSN|default('http://default:default@host:9090') }}"

partners:
    rstatbolt:
        init: https://bolt.rstat.org/cs/s.gif?p={{PARTNER}}&pi={partner_id}
        sync: https://bolt.rstat.org/cs/d.gif?p={{PARTNER}}&pi={partner_id}&ui={user_id}
