# set name of your service
name: cookiesync

# default paramenters
env: {{ ENV }}
listen: "{{ HOST|default('0.0.0.0')}}:{{PORT|default(8080) }}"
redis_dsn: "{{ REDIS_DSN|default('redis://redis:6379') }}"
ch_dsn: "{{CHP_DSN|default('http://default:default@host:9090') }}"

partners:
    local:
        init: https://stat.rock.dev/cs/s.gif?p={{PARTNER}}&pi={partner_id}
        sync: https://stat.rock.dev/cc/d.gif?p={{PARTNER}}&pi={partner_id}&ui={user_id}
    x011:
        init: https://0x011.xyz/cs/s.gif?p={{PARTNER}}&pi={partner_id}
        sync: https://0x011.xyz/cs/d.gif?p={{PARTNER}}&pi={partner_id}&ui={user_id}
