sequenceDiagram
    participant Side1
    participant Browser
    
    Browser-->>Side1: GET server/init?pt=side2
    Side1->>Browser: 302 Redirect target/sync?pt=side1&ptid=12345
    Browser->>Side2: GET target/sync?pt=side1&ptid=12345
    Side2->>Browser: 302 Redirect server/done?pt=side2&ptid=abcdef&uid=12345
    Browser->>Side1: GET server/done?pt=side2&ptid=abcdef&uid=12345
    Side1->>Browser: 200 OK image/gif
    